- core/src/main/java/com/amplitude/core/events/Plan.kt
- core/src/main/java/com/amplitude/core/utilities/JSONUtil.kt
> feat: add plan versionId support

- android/build.gradle
- android/src/main/java/com/amplitude/android/plugins/AndroidContextPlugin.kt
- update library name according to discussion with @justin-fiedler 
> feat: update library name

- android/src/main/java/com/amplitude/android/Amplitude.kt
- android/src/main/java/com/amplitude/android/plugins/AndroidContextPlugin.kt
- core/src/main/java/com/amplitude/core/events/EventOptions.kt
- core/src/main/java/com/amplitude/core/utilities/JSONUtil.kt
> feat: add event id support

- core/src/main/java/com/amplitude/core/Amplitude.kt
- core/src/main/java/com/amplitude/core/events/BaseEvent.kt
- core/src/main/java/com/amplitude/core/events/Identify.kt
- core/src/main/java/com/amplitude/core/events/Plan.kt
- core/src/main/java/com/amplitude/core/events/Revenue.kt
- core/src/main/java/com/amplitude/core/platform/plugins/IdentityEventSender.kt
- core/src/main/java/com/amplitude/core/utilities/AnalyticsEventReceiver.kt
- core/src/main/java/com/amplitude/core/utilities/JSON.kt
- core/src/main/java/com/amplitude/core/utilities/JSONUtil.kt
- release.config.js
- samples/java-android-app/src/main/java/com/amplitude/android/sample/MainActivity.java
- samples/java-android-app/src/main/java/com/amplitude/android/sample/MainApplication.java
- samples/kotlin-android-app/src/main/java/com/amplitude/android/sample/MainActivity.kt
- samples/kotlin-android-app/src/main/java/com/amplitude/android/sample/MainApplication.kt
- remove JSONObject from public interface
* Does your PR have a breaking change?:  yes
> feat: remove json object from public interface

- id/build.gradle
- id/src/main/java/com/amplitude/id/FileIdentityStorage.kt
- id/src/main/java/com/amplitude/id/IMIdentityStorage.kt
- id/src/main/java/com/amplitude/id/IdentityConfiguration.kt
- id/src/main/java/com/amplitude/id/IdentityContainer.kt
- id/src/main/java/com/amplitude/id/IdentityManager.kt
- id/src/main/java/com/amplitude/id/utilities/PropertiesFile.kt
- id/src/test/kotlin/com/amplitude/id/FileIdentityStorageTest.kt
- id/src/test/kotlin/com/amplitude/id/IdentityContainerTest.kt
- id/src/test/kotlin/com/amplitude/id/IdentityManagerTest.kt
- add unit tests in id module
- minor fixes
> feat: add unit tests in id module

- core/build.gradle
- core/src/main/java/com/amplitude/core/Amplitude.kt
- core/src/main/java/com/amplitude/core/Configuration.kt
- core/src/main/java/com/amplitude/core/events/BaseEvent.kt
- core/src/main/java/com/amplitude/core/events/GroupIdentifyEvent.kt
- core/src/main/java/com/amplitude/core/events/Revenue.kt
- core/src/main/java/com/amplitude/core/platform/EventPipeline.kt
- core/src/main/java/com/amplitude/core/platform/Mediator.kt
- core/src/main/java/com/amplitude/core/platform/plugins/AmplitudeDestination.kt
- core/src/main/java/com/amplitude/core/utilities/HttpClient.kt
- core/src/test/kotlin/com/amplitude/core/AmplitudeTest.kt
- core/src/test/kotlin/com/amplitude/core/ConfigurationTest.kt
- core/src/test/kotlin/com/amplitude/core/events/BaseEventTest.kt
- core/src/test/kotlin/com/amplitude/core/events/IdentifyTest.kt
- core/src/test/kotlin/com/amplitude/core/events/PlanTest.kt
- core/src/test/kotlin/com/amplitude/core/events/RevenueTest.kt
- core/src/test/kotlin/com/amplitude/core/utils/Mocks.kt
- core/src/test/kotlin/com/amplitude/core/utils/Plugins.kt
- add unit tests in core module
> feat: add unit tests in core module

- build.gradle
- common-android/build.gradle
- common-android/src/test/kotlin/com/amplitude/common/android/AndroidContextProviderTest.kt
Move unit tests for device info
> test: add tests for common android

- core/src/main/java/com/amplitude/core/Amplitude.kt
- core/src/main/java/com/amplitude/core/events/Identify.kt
- core/src/test/kotlin/com/amplitude/core/AmplitudeTest.kt
Expose more APIs for identify and group identify call, in order to be easily used in ampli kotlin v2 SDK. 
> feat: expose more api for support

- android/src/main/java/com/amplitude/android/Amplitude.kt
- android/src/main/java/com/amplitude/android/Configuration.kt
- android/src/main/java/com/amplitude/android/events/Export.kt
- android/src/main/java/com/amplitude/android/plugins/AndroidContextPlugin.kt
- core/src/main/java/com/amplitude/core/Configuration.kt
- core/src/main/java/com/amplitude/core/events/GroupIdentifyEvent.kt
- core/src/main/java/com/amplitude/core/events/Identify.kt
- core/src/main/java/com/amplitude/core/events/IdentifyEvent.kt
- core/src/main/java/com/amplitude/core/events/Plan.kt
- core/src/main/java/com/amplitude/core/events/Revenue.kt
- core/src/main/java/com/amplitude/core/events/RevenueEvent.kt
- core/src/main/java/com/amplitude/core/platform/plugins/ContextPlugin.kt
- core/src/test/kotlin/com/amplitude/core/AmplitudeTest.kt
- core/src/test/kotlin/com/amplitude/core/events/BaseEventTest.kt
- core/src/test/kotlin/com/amplitude/core/events/PlanTest.kt
- samples/kotlin-android-app/src/main/java/com/amplitude/android/sample/MainActivity.kt
- add plan in configuration
- add events export support
> feat: add plan in configuration and export

- core/src/main/java/com/amplitude/core/Amplitude.kt
- core/src/test/kotlin/com/amplitude/core/AmplitudeTest.kt
> feat: enable to pass the event options for all track call

- core/src/main/java/com/amplitude/core/Amplitude.kt
> feat: set the client userId and deviceId in identify call

- android/src/main/java/com/amplitude/android/Configuration.kt
> feat: make configuration to open class

- samples/kotlin-android-app/src/main/java/com/amplitude/android/sample/MainActivity.kt
- samples/kotlin-android-app/src/main/res/layout/activity_main.xml
Add button to kotlin example to send custom event, instead of sending the events when deploying the app, make it easier to test.
* Does your PR have a breaking change?:  
no
> feat: add button to kotlin example to send custom event

- core/src/main/java/com/amplitude/core/platform/EventPipeline.kt
Handle file not found issue for event pipeline upload
> fix: Handle file not found issue for event pipeline upload

- .github/workflows/release.yml
fix permission check for release action
> fix: authorize for release action

- core/src/main/java/com/amplitude/core/utilities/EventsFileManager.kt
fix unterminated array
fix expected literal value at character 0
> fix: invalid json array string for android file storage

- android/src/test/java/com/amplitude/android/AmplitudeTest.kt
- test: comment out unstable test for now
> test: comment out unstable test for now

- id/src/main/java/com/amplitude/id/utilities/PropertiesFile.kt
PR for fixing this [issue](https://github.com/amplitude/Amplitude-Kotlin/issues/54)
> fix: fix not call close in strict mode

- .github/workflows/jira-issue-create.yml
- id/src/main/java/com/amplitude/id/utilities/PropertiesFile.kt
> chore: use the github reusable workflow to create jira issue

- core/src/main/java/com/amplitude/core/utilities/JSONUtil.kt
add version_name to event json body
> fix: add version_name to event json body

- android/src/main/java/com/amplitude/android/Configuration.kt
- android/src/main/java/com/amplitude/android/events/Export.kt
- android/src/main/java/com/amplitude/android/plugins/AndroidContextPlugin.kt
- core/src/main/java/com/amplitude/core/Configuration.kt
- core/src/main/java/com/amplitude/core/events/BaseEvent.kt
- core/src/main/java/com/amplitude/core/events/EventOptions.kt
- core/src/main/java/com/amplitude/core/events/IngestionMetadata.kt
- core/src/main/java/com/amplitude/core/events/Plan.kt
- core/src/main/java/com/amplitude/core/platform/plugins/ContextPlugin.kt
- core/src/main/java/com/amplitude/core/utilities/JSONUtil.kt
- core/src/test/kotlin/com/amplitude/core/AmplitudeTest.kt
- core/src/test/kotlin/com/amplitude/core/events/BaseEventTest.kt
- core/src/test/kotlin/com/amplitude/core/events/IngestionMetadataTest.kt
- core/src/test/kotlin/com/amplitude/core/events/PlanTest.kt
- feat: add ingestion_metadata field
Add this option in the configuration, which can be used in the library wrapper/code generation/dynamic loading cases, for setting the `ingestion_metadata` information.
> feat: add ingestion_metadata field

- android/src/main/java/com/amplitude/android/plugins/AndroidContextPlugin.kt
- common-android/src/main/java/com/amplitude/common/android/AndroidContextProvider.kt
- allow adverting id and app set id to be null
- add null check to prevent exceptions
- fix for https://github.com/amplitude/Amplitude-Kotlin/issues/64
- fix app set id format
> fix: fix app set id null issue

- core/src/main/java/com/amplitude/core/Amplitude.kt
> fix: fix optOut

- android/src/main/java/com/amplitude/android/Amplitude.kt
> fix: add GetIngestionMetadataPlugin in android.Amplitude

- android/src/main/java/com/amplitude/android/plugins/AndroidContextPlugin.kt
> fix: fix other location info not auto populate

- android/src/main/java/com/amplitude/android/Amplitude.kt
- core/src/main/java/com/amplitude/core/Amplitude.kt
change isBuilt to val from lateinit var
> fix: DXOC-200 lateinit var isBuilt not initialized

- android/build.gradle
- android/src/test/java/com/amplitude/android/AmplitudeTest.kt
> test: ip and country test

- android/src/main/java/com/amplitude/android/Configuration.kt
> fix: make trackingOptions able to overwrite in configuration

- .github/workflows/docs.yml
- .github/workflows/pull-request-test.yml
- .github/workflows/release.yml
- .github/workflows/semantic-pr.yml
- update github actions for node 12 warnings
> chore: update github actions to reduce node 12 warnings

- core/src/main/java/com/amplitude/core/platform/intercept/IdentifyInterceptFileStorageHandler.kt
- prevent index out-of-bound exception
- catch any other possible exception
> fix: catch and prevent index out bound exception

- core/src/main/java/com/amplitude/core/platform/intercept/IdentifyInterceptFileStorageHandler.kt
- core/src/main/java/com/amplitude/core/platform/intercept/IdentifyInterceptInMemoryStorageHandler.kt
- core/src/main/java/com/amplitude/core/platform/intercept/IdentifyInterceptStorageHandler.kt
- core/src/main/java/com/amplitude/core/platform/intercept/IdentifyInterceptor.kt
Remove unused code - unused since version 1.8.2.
> chore: remove unused code in identify interceptor logic

- core/src/main/java/com/amplitude/core/events/Identify.kt
I tried to reproduce [ConcurrentModificationExceptions bug](https://github.com/amplitude/Amplitude-Kotlin/issues/115). The exception is reproduced if some Identify object is shared and modified between `identify` calls.
Current Identify implementation is not thread-safe.
Now I added synchronized access to mutation methods (`clearAll`, `setUserProperty`) and properties cloning (2 top levels). Not sure if the fix helps in all cases (including [ConcurrentModificationExceptions bug](https://github.com/amplitude/Amplitude-Kotlin/issues/115)).
> fix: thread-safe Identify object

- .github/workflows/jira-issue-create.yml
* update issue creation to AMP project
* Does your PR have a breaking change?: No
> chore: update issue creation to AMP project

- samples/java-android-app/README.md
- samples/kotlin-android-app/README.md
Added READMEs to the sample Android apps
* Does your PR have a breaking change?:  Nope
> chore: Add readme to samples

- core/src/main/java/com/amplitude/core/platform/EventPipeline.kt
- core/src/main/java/com/amplitude/core/platform/intercept/IdentifyInterceptor.kt
- core/src/main/java/com/amplitude/core/utilities/LoggerExtensions.kt
- samples/java-android-app/src/main/java/com/amplitude/android/sample/MainApplication.java
- Logging stack traces when an exception is thrown
- FIxing sample app that was missing an method override
> chore: Add stack traces in exceptions and fix sample app

- README.md
This PR updates the SDK version.
> chore: Update the SDK version

- .github/workflows/pull-request-test.yml
- .github/workflows/release.yml
This PR refactors the release CI to use the `pull-request-test.yaml` workflow to test the SDK before a release.
> ci: refactor release CI

- android/src/main/java/com/amplitude/android/plugins/AndroidLifecyclePlugin.kt
Moving Autocapture plugin handling to main thread.
> fix: autocapture not main thread crash

- .github/workflows/pull-request-test.yml
- android/src/test/java/com/amplitude/android/AmplitudeSessionTest.kt
- android/src/test/java/com/amplitude/android/AmplitudeTest.kt
- core/build.gradle
- id/src/main/java/com/amplitude/id/utilities/PropertiesFile.kt
- id/src/test/kotlin/com/amplitude/id/FileIdentityStorageTest.kt
- id/src/test/kotlin/com/amplitude/id/IdentityContainerTest.kt
- id/src/test/kotlin/com/amplitude/id/utilities/PropertiesFileTest.kt
Realized that all tests weren't running in our build system. Trying to fix that. 
> chore: get all tests to run in build

- android/src/main/java/com/amplitude/android/Amplitude.kt
Parent build process is causing concurrent modification issue with class that extends it.
We moved filed init into parent build block.
> fix: autocapture observer null pointer exception

- .github/ISSUE_TEMPLATE/Bug_report.md
Updating the bug reporting template for sdk version
> docs: Bug template update

- android/src/main/java/com/amplitude/android/plugins/AndroidContextPlugin.kt
- common-android/src/main/java/com/amplitude/common/android/AndroidContextProvider.kt
> refactor: cleanup prior to context provider changes

- android/src/main/java/com/amplitude/android/utilities/DefaultEventUtils.kt
> fix: mark event utils as deprecated

- .github/workflows/release.yml
Update release ubuntu version to latest as 20.4 is deprecated and removed.
> ci: update ubuntu to latest

- android/src/test/kotlin/com/amplitude/core/network/NetworkTrackingPluginTest.kt
- core/src/main/java/com/amplitude/core/network/NetworkTrackingPlugin.kt
We only want the URL without query/fragment for the `[Amplitude] URL` property.
> fix: send URL without fragment/query

- core/src/main/java/com/amplitude/core/utilities/EventsFileManager.kt
> fix: filter unfinished files that don't exist

- android/src/main/java/com/amplitude/android/utilities/DefaultEventUtils.kt
> fix: make sure that amplitude is built before writing on storage

- core/src/main/java/com/amplitude/core/Constants.kt
> fix: event type for network tracking

- android/src/main/java/com/amplitude/android/AutocaptureOptions.kt
- android/src/main/java/com/amplitude/android/plugins/AndroidLifecyclePlugin.kt
- android/src/test/kotlin/com/amplitude/android/ConfigurationTest.kt
> refactor: remove experimental annotation from element interactions

- android/build.gradle.kts
- android/src/main/java/com/amplitude/android/internal/fragments/AutocaptureFragmentLifecycleCallbacks.kt
- android/src/main/java/com/amplitude/android/internal/fragments/FragmentActivityHandler.kt
- android/src/main/java/com/amplitude/android/plugins/AndroidNetworkConnectivityCheckerPlugin.kt
- android/src/main/java/com/amplitude/android/utilities/AndroidNetworkConnectivityChecker.kt
- android/src/main/java/com/amplitude/android/utilities/AndroidNetworkListener.kt
- android/src/main/java/com/amplitude/android/utilities/DefaultEventUtils.kt
- android/src/test/kotlin/com/amplitude/android/plugins/AndroidLifecyclePluginTest.kt
- android/src/test/kotlin/com/amplitude/android/plugins/AndroidNetworkConnectivityCheckerPluginTest.kt
- android/src/test/kotlin/com/amplitude/android/utilities/AndroidNetworkConnectivityCheckerTest.kt
- samples/kotlin-android-app/build.gradle.kts
> refactor: bump min sdk to 21

- android/build.gradle.kts
- samples/kotlin-android-app/build.gradle.kts
> refactor: bump compile sdk to 35

- build.gradle.kts
- gradle/libs.versions.toml
- samples/kotlin-android-app/build.gradle.kts
- samples/kotlin-android-app/src/main/AndroidManifest.xml
- samples/kotlin-android-app/src/main/java/com/amplitude/android/sample/ComposeActivity.kt
- samples/kotlin-android-app/src/main/java/com/amplitude/android/sample/ComposeAdvancedActivity.kt
- samples/kotlin-android-app/src/main/java/com/amplitude/android/sample/LauncherActivity.kt
- samples/kotlin-android-app/src/main/java/com/amplitude/android/sample/MainApplication.kt
- samples/kotlin-android-app/src/main/java/com/amplitude/android/sample/XmlAdvancedActivity.kt
- samples/kotlin-android-app/src/main/java/com/amplitude/android/sample/XmlViewActivity.kt
Basic port of Compose, adding newer elements for auto-capture tests soon
> chore: add compose to sample app

- android/src/main/java/com/amplitude/android/utilities/DefaultEventUtils.kt
> fix: add activity title as the first option, before falling back to other options

- android/build.gradle.kts
- android/src/test/kotlin/com/amplitude/MainDispatcherRule.kt
- android/src/test/kotlin/com/amplitude/android/AmplitudeRobolectricTests.kt
- android/src/test/kotlin/com/amplitude/android/AmplitudeSessionTest.kt
- android/src/test/kotlin/com/amplitude/android/AmplitudeTest.kt
- android/src/test/kotlin/com/amplitude/android/IdentifyInterceptorTest.kt
- android/src/test/kotlin/com/amplitude/android/ResponseHandlerIntegrationTest.kt
- android/src/test/kotlin/com/amplitude/android/internal/gestures/AutocaptureGestureListenerClickTest.kt
- android/src/test/kotlin/com/amplitude/android/migration/MigrationManagerTest.kt
- android/src/test/kotlin/com/amplitude/android/migration/RemnantDataMigrationTest.kt
- android/src/test/kotlin/com/amplitude/android/utilities/AndroidLoggerProviderTest.kt
- android/src/test/kotlin/com/amplitude/android/utilities/AndroidNetworkConnectivityCheckerTest.kt
- build.gradle.kts
- core/build.gradle.kts
- core/src/test/kotlin/com/amplitude/core/platform/EventPipelineTest.kt
- gradle/libs.versions.toml
- samples/kotlin-android-app/src/main/AndroidManifest.xml
- samples/kotlin-android-app/src/main/java/com/amplitude/android/sample/TroubleShootingPlugin.kt
- Bump coroutines version
- Make Amplitude Android tests Robolectric for Main Looper support
- Added Main Looper Rule
- Migrated Robolectric tests to Junit4
> ci: Fix silent test fails
