event-bridge/build.gradle
event-bridge/src/main/java/com/amplitude/eventbridge/EventBridge.kt
event-bridge/src/main/java/com/amplitude/eventbridge/EventBridgeContainer.kt
event-bridge/src/test/kotlin/com/amplitude/eventbridge/EventBridgeContainerTest.kt
event-bridge/src/test/kotlin/com/amplitude/eventbridge/EventBridgeTest.kt

- add unit tests in event bridge module

feat: add unit tests in event bridge module

---

android/build.gradle
build.gradle
common-jvm/build.gradle
common/build.gradle
event-bridge/build.gradle
gradle.properties
id/build.gradle
samples/java-android-app/build.gradle
samples/kotlin-android-app/build.gradle

- Fix android aar package
- Make it to be a fat aar for now

fix: fix android aar issue

---

android/build.gradle
android/src/main/java/com/amplitude/android/Amplitude.kt
android/src/main/java/com/amplitude/android/plugins/AndroidContextPlugin.kt
android/src/test/java/com/amplitude/android/AmplitudeTest.kt
core/src/main/java/com/amplitude/core/Amplitude.kt
core/src/test/kotlin/com/amplitude/core/AmplitudeTest.kt

This PR adds the `#reset` method, which does the following things:
- `setUserId` to null
- `setDeviceId` to new generated one
* Does your PR have a breaking change?:  
No

feat: add reset method to reset userId and deviceId

---

android/build.gradle
android/src/test/java/com/amplitude/android/AmplitudeTest.kt

This PR fixes the unstable coroutine test, which was commented out to unblock last release.
Refer to: https://developer.android.com/kotlin/coroutines/test#injecting-test-dispatchers

test: fix unstable coroutine test

---

android/src/main/java/com/amplitude/android/Amplitude.kt
android/src/main/java/com/amplitude/android/plugins/AndroidLifecyclePlugin.kt
android/src/main/java/com/amplitude/android/utilities/AndroidStorage.kt
core/src/main/java/com/amplitude/core/Amplitude.kt
core/src/main/java/com/amplitude/core/Storage.kt
core/src/main/java/com/amplitude/core/utilities/EventsFileManager.kt
core/src/main/java/com/amplitude/core/utilities/FileResponseHandler.kt
core/src/main/java/com/amplitude/core/utilities/FileStorage.kt
core/src/main/java/com/amplitude/core/utilities/InMemoryStorage.kt

* Put mutex to class companion to lock for possible multi instance access
* Reduce duplicate events requests from same event file
* Put curFile reference to companion and managed by apiKey
* Handle invalid events json string: delete file and clean up callback map

fix: Unterminated arrays caused by multi client instances with same name and api key

---

android/src/main/java/com/amplitude/android/Configuration.kt
android/src/test/java/com/amplitude/android/ConfigurationTest.kt

This PR updates the configuration fields in Android, to be editable, see https://github.com/amplitude/Amplitude-Kotlin/issues/65.

feat: allow android configuration values to be updated

---

core/src/main/java/com/amplitude/core/platform/plugins/ContextPlugin.kt

In android SDK the IP address can be get on the server side. 
The old android SDK is using the HTTP API v1. We don't need to set anything in order to use the remote IP. https://github.com/amplitude/amplitude/blob/master/event/converters/sdk.py#L164
But the Kotlin SDK is using the HTTP API V2, which required to pass `ip="$remote"` https://github.com/amplitude/amplitude/blob/master/event/converters/http_event.py#L528.
In order to fix the IP is null in kotlin SDK we need to pass the `ip="$remote"`.

fix: enable the remote ip

---

core/src/main/java/com/amplitude/core/Amplitude.kt
core/src/main/java/com/amplitude/core/platform/plugins/GetAmpliExtrasPlugin.kt
core/src/test/kotlin/com/amplitude/core/AmplitudeTest.kt
core/src/test/kotlin/com/amplitude/core/platform/plugins/GetAmpliExtrasPluginTest.kt

This PR adds a `GetAmpliExtrasPlugin` as enrichment plugin for retrieving the ampli information from extra field, currently will be used for the ingestion metadata injection.

feat: add ampli extra plugin for attaching ingestion metadata information

---

android/src/main/java/com/amplitude/android/plugins/AndroidContextPlugin.kt
core/src/test/kotlin/com/amplitude/core/AmplitudeTest.kt

Added the IP = "\$remote" in AndroidContextPlugin. 
Added IP test.

fix: fix the ip address not catch issue

---

android/src/main/java/com/amplitude/android/Amplitude.kt
android/src/main/java/com/amplitude/android/plugins/AndroidContextPlugin.kt
android/src/test/java/com/amplitude/android/AmplitudeTest.kt
core/src/main/java/com/amplitude/core/Amplitude.kt
core/src/main/java/com/amplitude/core/events/BaseEvent.kt

Session-specific logic moved from ContextPlugin to avoid race conditions

fix: move session-specific logic from ContextPlugin to avoid race conditions

---

android/src/main/java/com/amplitude/android/Amplitude.kt
android/src/test/java/com/amplitude/android/AmplitudeTest.kt
core/src/main/java/com/amplitude/core/Amplitude.kt
core/src/main/java/com/amplitude/core/utilities/InMemoryStorage.kt

1. Current session restore logic didn't work correctly due to Kotlin initialization order (property initializes, `init` blocks, child/parent inheritance). The logic is extracted to a separate `init` block.
2. Added a test for the session restore logic.
3. Session-specific code is moved from coroutines to let it be executed synchronously and avoid possible data-race issues. 
4. Some unnecessary code is removed (including `previousSessionId` property)
5. Fixed bug in `InMemoryStorage` - `contains` was used instead of `containsKey`

fix: restore previous session data on app opening

---

android/src/main/java/com/amplitude/android/Amplitude.kt
android/src/main/java/com/amplitude/android/Timeline.kt
android/src/test/java/com/amplitude/android/AmplitudeTest.kt
core/src/main/java/com/amplitude/core/Amplitude.kt
core/src/main/java/com/amplitude/core/platform/Timeline.kt

All session-related logic is extracted to new Timeline class.

fix: move session-specific logic to Timeline

---

android/src/main/java/com/amplitude/android/Amplitude.kt
core/src/main/java/com/amplitude/core/Amplitude.kt

`build()` body calls `isBuilt.await()` (somewhere in nested subcalls). The body was started immediately and can use uninitialized `isBuilt`. Now the 'build' body is started lazily just after `isBuilt` was initialized.

fix: start build() lazily

---

android/src/main/java/com/amplitude/android/Amplitude.kt
core/src/main/java/com/amplitude/core/Amplitude.kt
core/src/main/java/com/amplitude/core/utilities/FileStorage.kt
id/build.gradle
id/src/main/java/com/amplitude/id/FileIdentityStorage.kt
id/src/main/java/com/amplitude/id/IdentityConfiguration.kt
id/src/main/java/com/amplitude/id/utilities/PropertiesFile.kt
id/src/test/kotlin/com/amplitude/id/FileIdentityStorageTest.kt
id/src/test/kotlin/com/amplitude/id/utilities/PropertiesFileTest.kt

This PR is to address the:
```
Fatal Exception: java.lang.IllegalArgumentException
Malformed \uxxxx encoding
```
- I cannot reproduce the same error with setting the `device_id` with a special char, like "时间" (any Chinese char), "\u0000". So I think this should be related to the file path, instead of the content.
- I found an article mentioning the similar problem: https://www.ibm.com/support/pages/error-javalangillegalargumentexception-malformed-uxxxx-encoding-when-start-cognos-analytics
So I think it might be the case that the user is running the app inside the Windows machine within the simulator, and have a customized storage configured with "\user" or "\uxxx" inside the path, then when the file system tries to get that file, it treats the \u as unicode. Note I tried to hack my …

fix: add error handling and logging for file load crash issue

---

id/src/main/java/com/amplitude/id/utilities/PropertiesFile.kt
id/src/test/kotlin/com/amplitude/id/utilities/PropertiesFileTest.kt

Expection catch and log for PropertiesFile.save()
Change more general Exception catch for PropertiesFile.load()
Unit test for added function

fix: Add Index out of bound exception handling for PropertiesFile.save()

---

android/src/main/java/com/amplitude/android/utilities/AndroidLoggerProvider.kt
android/src/main/java/com/amplitude/android/utilities/AndroidStorage.kt
android/src/test/java/com/amplitude/android/utilities/AndroidLoggerProviderTest.kt
core/src/main/java/com/amplitude/core/Amplitude.kt
core/src/main/java/com/amplitude/core/utilities/ConsoleLoggerProvider.kt
core/src/main/java/com/amplitude/core/utilities/FileResponseHandler.kt
core/src/main/java/com/amplitude/core/utilities/FileStorage.kt
core/src/test/kotlin/com/amplitude/core/utilities/ConsoleLoggerProviderTest.kt

- feat: add log.debug to send event and handle response
- https://github.com/amplitude/Amplitude-Kotlin/issues/94
- Expose the visibility of handling the responses
Change the logger provider to provide a singleton instance of `Logger`, otherwise, when we set `amplitude.logger.logMode = Logger.LogMode.DEBUG`, it won't work globally.

feat: add log.debug to send event and handle response

---

android/src/main/java/com/amplitude/android/Amplitude.kt
android/src/main/java/com/amplitude/android/Timeline.kt
android/src/test/java/com/amplitude/android/AmplitudeTest.kt

Return 'sessionId' property to Amplitude class

fix: return 'sessionId' property to Amplitude class

---

android/src/test/java/com/amplitude/android/IdentifyInterceptorTest.kt
core/src/main/java/com/amplitude/core/platform/intercept/IdentifyInterceptFileStorageHandler.kt
core/src/main/java/com/amplitude/core/platform/intercept/IdentifyInterceptInMemoryStorageHandler.kt
core/src/main/java/com/amplitude/core/platform/intercept/IdentifyInterceptStorageHandler.kt
core/src/test/kotlin/com/amplitude/core/IdentifyInterceptTest.kt

- filter out null user properties in identify intercept

fix: filter null values in identify intercept

---

android/src/main/java/com/amplitude/android/Amplitude.kt
android/src/test/java/com/amplitude/android/AmplitudeOtherTest.kt
android/src/test/java/com/amplitude/android/AmplitudeRobolectricTests.kt

When set `optOut = true`, we still track the session events. Please check here for the origin [issue](https://amplitude.atlassian.net/browse/DXOC-734?atlOrigin=eyJpIjoiMzBkNGU3NGQ2MjlkNDI4MmE0ZDhmYzhjODFjM2E4Y2QiLCJwIjoiaiJ9). 
* Does your PR have a breaking change?:    No

fix: fix log session event when optOut is true

---

android/src/test/java/com/amplitude/android/IdentifyInterceptorTest.kt
core/src/main/java/com/amplitude/core/platform/intercept/IdentifyInterceptor.kt
core/src/test/kotlin/com/amplitude/core/IdentifyInterceptTest.kt

- update identify transfer to merge identify only for now.

fix: update identify transfer to merge identify only

---

android/src/main/java/com/amplitude/android/Configuration.kt

Enable `migrateLegacyData` configuration option by default.

fix: enable legacy data migration by default

---

android/src/main/java/com/amplitude/android/Timeline.kt

Wait until build (including possible legacy data migration) is finished - otherwise legacy data (previous session id, last event time/id) can be not saved to the storage yet.
The fix doesn't help with original issue (mailformed json).

fix: wait until build (including possible legacy data migration) is finished

---

.github/workflows/release.yml

fix semantic release by locking to 1.2.0

chore: fix semantic release by locking to 1.2.0

---

android/src/main/java/com/amplitude/android/Amplitude.kt
android/src/main/java/com/amplitude/android/migration/ApiKeyStorageMigration.kt
android/src/main/java/com/amplitude/android/migration/StorageKeyMigration.kt
android/src/main/java/com/amplitude/android/utilities/AndroidStorage.kt
android/src/test/java/com/amplitude/android/migration/StorageKeyMigrationTest.kt
core/src/main/java/com/amplitude/core/Storage.kt
core/src/main/java/com/amplitude/core/utilities/EventsFileManager.kt
core/src/main/java/com/amplitude/core/utilities/FileStorage.kt
core/src/main/java/com/amplitude/core/utilities/InMemoryStorage.kt

Migrate 'api key' storage data to 'instance name' storage.
Implementation and test are similar to Amplitude-Swift (https://github.com/amplitude/Amplitude-Swift/pull/63)

feat: migrate 'api key' storage data to 'instance name' storage

---

android/src/main/java/com/amplitude/android/migration/DatabaseStorage.kt
android/src/test/java/com/amplitude/android/migration/DatabaseStorageTest.kt
android/src/test/java/com/amplitude/android/migration/RemnantDataMigrationTest.kt
android/src/test/resources/not_db_file

Possible fix for [DataMigration NotImplementedError](https://github.com/amplitude/Amplitude-Kotlin/issues/146).
Data migration already checks if the Database file exists and skips the migration if it doesn't.
But if the file exists but it is not a sqlite database for some reason - NotImplemented error is thrown.
Now migration is skipped in both cases.

fix: do not throw NotImplemented error for existing "legacy database"file if the file is not a sqlite file

---

android/src/main/java/com/amplitude/android/utilities/DefaultEventUtils.kt
android/src/test/java/com/amplitude/android/plugins/AndroidLifecyclePluginTest.kt

fix: skip deep link event when url is missing
This PR filters the deep link event (triggered with activity creation) by only limiting to the case when `intent.data` is available, this can potentially avoid some noisy.
Note this is a breaking change, the existing users will probably see a drop in the event volume, but I think this change aligns more to a bug fix.

fix: skip deep link event when url is missing

---

core/src/main/java/com/amplitude/core/utilities/HttpClient.kt

https://amplitude.atlassian.net/browse/AMP-87210
Adding client_upload_time so that when client-side clock is drifted, backend can [correct it](https://discourse.amplitude.com/t/is-it-possible-to-enable-event-time-adjustments-if-discrepancy-is-less-than-60-seconds/11627/5?u=justin)

feat: add client upload time

---

README.md

- Remove "beta" in README
- This PR is mainly for releasing another patch release to Maven as `v1.12.0` is only released to Github but not to Maven

fix: remove beta and release to Maven

---

core/src/main/java/com/amplitude/core/utilities/HttpClient.kt
core/src/test/kotlin/com/amplitude/core/utilities/HttpClientTest.kt

* Fixes #159, [AMP-88899](https://amplitude.atlassian.net/browse/AMP-88899)
* Correctly handles `client_upload_time` when `minIdLength` is set in the configuration
* Added tests for HttpClient
* Does your PR have a breaking change?: No
[AMP-88899]: https://amplitude.atlassian.net/browse/AMP-88899?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: correctly format client_upload_time in HTTP request when minIdLength is set

---

.github/workflows/pull-request-test.yml

Save `./gradlew` commands results as artifacts

ci: save reports as artifacts

---

android/src/main/java/com/amplitude/android/Configuration.kt
android/src/main/java/com/amplitude/android/plugins/AndroidContextPlugin.kt
android/src/test/java/com/amplitude/android/AmplitudeTest.kt
core/src/main/java/com/amplitude/core/Amplitude.kt
core/src/main/java/com/amplitude/core/Configuration.kt
core/src/main/java/com/amplitude/core/platform/plugins/ContextPlugin.kt
core/src/test/kotlin/com/amplitude/core/AmplitudeTest.kt

Adds `deviceId` to `Configuration` options to set the initial deviceId (instead of generating it, or reading from storage)
```
val deviceId = "test device id"
val amplitude = Amplitude(Configuration(deviceId = deviceId))
amplitude.isBuilt.invokeOnCompletion {
assertEqual(deviceId, amplitude.getDeviceId());
}
```

feat: added deviceId to Configuration options

---

android/src/main/java/com/amplitude/android/Amplitude.kt
android/src/main/java/com/amplitude/android/Configuration.kt
android/src/main/java/com/amplitude/android/Timeline.kt
android/src/test/java/com/amplitude/android/AmplitudeTest.kt
core/src/main/java/com/amplitude/core/Configuration.kt

* allow setting isessionId in initial configuration

feat: allow setting sessionId in initial configuration

---

.github/workflows/docs.yml
.github/workflows/pull-request-test.yml
.github/workflows/release.yml
android/src/main/java/com/amplitude/android/migration/ApiKeyStorageMigration.kt
android/src/main/java/com/amplitude/android/utilities/AndroidStorage.kt
android/src/test/java/com/amplitude/android/migration/StorageKeyMigrationTest.kt
android/src/test/java/com/amplitude/android/utilities/AndroidStorageTest.kt
core/src/main/java/com/amplitude/core/Amplitude.kt
core/src/main/java/com/amplitude/core/Storage.kt
core/src/main/java/com/amplitude/core/platform/EventPipeline.kt
core/src/main/java/com/amplitude/core/utilities/Diagnostics.kt
core/src/main/java/com/amplitude/core/utilities/EventsFileManager.kt
core/src/main/java/com/amplitude/core/utilities/FileStorage.kt
core/src/main/java/com/amplitude/core/utilities/HttpClient.kt
core/src/main/java/com/amplitude/core/utilities/JSONUtil.kt
core/src/test/kotlin/com/amplitude/core/utilities/DiagnosticsTest.kt
core/src/test/kotlin/com/amplitude/core/utilities/EventsFileManagerTest.kt
core/src/test/kotlin/com/amplitude/core/utilities/HttpClientTest.kt

- update storage for better thread safety

feat: switch storage for better thread safety

---

id/src/main/java/com/amplitude/id/utilities/PropertiesFile.kt

* Fix for #172 
* I added additional error handling to catch the AssertionError and prevent a crash.
* Since this error is internal to Android, I don’t think there is much we can do to fix it.

fix: catch potential internal Errors from Properties.save() and load()

---

core/src/main/java/com/amplitude/core/utilities/HttpClient.kt
core/src/main/java/com/amplitude/core/utilities/Response.kt
core/src/test/kotlin/com/amplitude/core/utilities/HttpClientTest.kt

This PR fixes two issues
1. Allow empty response bodies for successful requests (#184)
2. When the server returns a 503, the response body is not an HTML page and not a json object. So try parsing response and don't fail (#163)

fix: Only parse response body when a body is expected

---

core/src/main/java/com/amplitude/core/utilities/Diagnostics.kt
core/src/test/kotlin/com/amplitude/core/utilities/DiagnosticsTest.kt

- only take unique error logs
- control how many error logs we send each time

fix: only take unique error logs and control limit

---

android/src/main/java/com/amplitude/android/Amplitude.kt
android/src/main/java/com/amplitude/android/Timeline.kt
android/src/test/java/com/amplitude/android/AmplitudeTest.kt
core/src/main/java/com/amplitude/core/Amplitude.kt

[AMP-96567]
*  ensure sessionId is set before Plugin.setup is called
[AMP-96567]: https://amplitude.atlassian.net/browse/AMP-96567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: session id not set before plugin setup

---

android/src/main/java/com/amplitude/android/Amplitude.kt
android/src/main/java/com/amplitude/android/Timeline.kt
android/src/main/java/com/amplitude/android/utilities/Session.kt
android/src/test/java/com/amplitude/android/AmplitudeSessionTest.kt
android/src/test/java/com/amplitude/android/AmplitudeTest.kt
core/src/main/java/com/amplitude/core/Amplitude.kt

* fix storage timing issue from last commit
* after the last change sometimes deviceId would not be loaded in time for the session events. This fix resolves that issue by moving the storage creation back into the proper coroutine.
* set sessionId before plugin.setup
* this is once again part of buildInternal so that the storage is fully setup
* We load the initial session id prior to the internal calls to `add(plugin)`
* Note - If plugins require accurate values for `sessionId` in `setup` they must be added via config e.g. `amplitude(Configuration(plugins = listOf(pluginThatNeedsSessionIdInSetup)`
* Improved sessionId check in Plugin.setup to verify that a valid session id is set (not -1) 

fix: fix storage timing issue, set sessionId before plugin.setup

---

android/src/main/java/com/amplitude/android/Amplitude.kt
android/src/main/java/com/amplitude/android/Timeline.kt
android/src/test/java/com/amplitude/android/AmplitudeTest.kt
core/src/main/java/com/amplitude/core/platform/Timeline.kt

This PR fixes a race condition where an event gets processed after the app enters the foreground but before amplitude gets to create a new session.
Instead of setting a flag in Amplitude when the app enters foreground, we now treat all events fired before amplitude's foreground event is fired as background events. 

fix: fix race condition where an event can be processed before a session gets extended

---

.github/workflows/pull-request-test.yml
gradle/wrapper/gradle-wrapper.properties

Changes the JDK version for the build/test workflow.

ci: Change CI JDK version to 17

---

android/src/main/java/com/amplitude/android/internal/ViewTarget.kt
android/src/main/java/com/amplitude/android/internal/gestures/AutocaptureGestureListener.kt
android/src/main/java/com/amplitude/android/internal/locators/AndroidViewTargetLocator.kt
android/src/main/java/com/amplitude/android/internal/locators/ComposeViewTargetLocator.java
android/src/main/java/com/amplitude/android/utilities/DefaultEventUtils.kt
android/src/test/java/com/amplitude/android/internal/gestures/AutocaptureGestureListenerClickTest.kt

This PR adds support for tracking the localized text of Android Views in Autocapture.
`[Amplitude] Target Text`, the text of the clickable target in Android Views.

fix: Add target text capture for Android Views in Autocapture

---

android/src/main/java/com/amplitude/android/internal/locators/AndroidViewTargetLocator.kt

This PR limits tracking clickable elements text to buttons only.

fix: Track buttons text only for clickable elements in Autocapture

---

android/build.gradle
android/src/main/java/com/amplitude/android/internal/fragments/AutocaptureFragmentLifecycleCallbacks.kt
android/src/main/java/com/amplitude/android/internal/fragments/FragmentActivityHandler.kt
android/src/main/java/com/amplitude/android/plugins/AndroidLifecyclePlugin.kt
android/src/main/java/com/amplitude/android/utilities/ComposeUtils.kt
android/src/main/java/com/amplitude/android/utilities/DefaultEventUtils.kt
android/src/main/java/com/amplitude/android/utilities/LoadClass.kt

This PR adds support for capturing top-level Fragments with the `screenView` configuration of Autocapture.
- `[Amplitude] Fragment Viewed`, this event is fired when the Fragment becomes visible on the screen.
- `[Amplitude] Fragment Class`, the canonical class name of the Fragment.
- `[Amplitude] Fragment Identifier`, the entry name of the fragment based on its internal id. The entry name is the id specified in the layout.
-  `[Amplitude] Screen Name`
- `[Amplitude] Fragment Tag`, the tag attached to the fragment.

feat: Capture top-level Fragments with Autocapture

---

android/src/main/java/com/amplitude/android/migration/IdentityStorageMigration.kt

Don't delete the old profile file since we are not doing a major version upgrade. Deleting this file prevents will cause issues when a customer rolls back the Amplitude SDK to an older version or rollsback their app.

fix: don't delete old profile file for backwards compatibility

---

android/src/main/java/com/amplitude/android/migration/DatabaseStorage.kt

Adding support for API version 35's sqlite library. The field table is non nullable.

fix: type mismatch on `queryDb`

---

android/src/main/java/com/amplitude/android/Amplitude.kt
android/src/main/java/com/amplitude/android/plugins/AndroidLifecyclePlugin.kt
android/src/main/java/com/amplitude/android/utilities/ActivityLifecycleObserver.kt
android/src/main/java/com/amplitude/android/utilities/DefaultEventUtils.kt
android/src/test/java/com/amplitude/android/plugins/AndroidLifecyclePluginTest.kt
samples/kotlin-android-app/src/main/java/com/amplitude/android/sample/MainApplication.kt

Autocapture fix for missing and broken event sequence

fix: autocapture missing events fix

---

README.md

The 💯  Developer Center hyperlink was pointing to a broken link and directing users to the homepage of our docs (https://amplitude.com/docs) rather than directly to the Kotlin SDK docs. Points the hyperlink to the current docs (https://amplitude.com/docs/sdks/analytics/android/android-kotlin-sdk).
* [ ✅] Does your PR title have the correct [title format](https://github.com/amplitude/Amplitude-Kotlin/blob/main/CONTRIBUTING.md#pr-commit-title-conventions)?

chore: Update Developer Center docs hyperlink

---

core/src/main/java/com/amplitude/core/events/BaseEvent.kt
core/src/main/java/com/amplitude/core/events/EventOptions.kt
core/src/main/java/com/amplitude/core/events/Revenue.kt
core/src/main/java/com/amplitude/core/utilities/JSONUtil.kt
core/src/test/kotlin/com/amplitude/core/events/RevenueTest.kt

Adding ability to track revenue currency

fix: adding ability to track revenue currency

---

core/src/main/java/com/amplitude/core/Configuration.kt
samples/kotlin-android-app/src/main/java/com/amplitude/android/sample/CustomOkHttpClient.kt
samples/kotlin-android-app/src/main/java/com/amplitude/android/sample/MainApplication.kt

- Making `getApiHost` accessible to customers
- Update example to show how to use custom clients with config

fix: initialize custom http client with configuration

---

android/consumer-rules.pro

Adds `consumer-rules.pro` to fix errors when minify is enabled and `useAppSetIdForDeviceId = true`.
Fixes https://github.com/amplitude/Amplitude-Kotlin/issues/205
Tested locally with both minify and app set flag enabled.

fix: add consumer-rules for useAppSetIdForDeviceId = true

---

android/src/main/java/com/amplitude/android/plugins/AndroidContextPlugin.kt
common-android/build.gradle
common-android/src/main/java/com/amplitude/common/android/AndroidContextProvider.kt
common-android/src/test/kotlin/com/amplitude/common/android/AndroidContextProviderTest.kt

- this should now respect the value set from tracking options
Adds `shouldTrackAppSetId` to context provider, this respects the value set from tracking options.

fix: respect play services flags inside context provider

---

android/src/main/java/com/amplitude/android/Amplitude.kt
core/src/main/java/com/amplitude/core/Amplitude.kt

This is an attempt to fix an ANR: it seems that the stack trace point to the call on `amplitude.flush()` from `AndroidNetworkConnectivityCheckerPlugin` which happens Activity onCreate. 
In this PR, we ensure that flush is uniformly launched on the Amplitude dispatcher.

fix: ANR fix attempt on network change

---

core/src/main/java/com/amplitude/core/platform/Mediator.kt
core/src/main/java/com/amplitude/core/platform/Timeline.kt
core/src/test/kotlin/com/amplitude/core/AmplitudeTest.kt
core/src/test/kotlin/com/amplitude/core/platform/MediatorTest.kt

Removes `synchronized` blocks on `Mediator` in favor of `CopyOnWriteArrayList` instead.
It would be good to review this PR on a per commit basis.

fix: remove synchronized on mediator

---

core/src/test/kotlin/com/amplitude/core/platform/MediatorTest.kt

Fix flaky test for simulating work and adding a plugin using multiple threads

fix: Mediator flaky test 

---

core/src/main/java/com/amplitude/core/platform/EventPipeline.kt
core/src/main/java/com/amplitude/core/utilities/http/AnalyticsResponse.kt
core/src/main/java/com/amplitude/core/utilities/http/HttpClient.kt
samples/kotlin-android-app/src/main/java/com/amplitude/android/sample/CustomOkHttpClient.kt

Fix warnings and formatting for some of the files prior to refactoring

fix: reformatting and warning fixes for upload ordering ticket 

---

android/src/main/java/com/amplitude/android/internal/ViewHierarchyScanner.kt
android/src/main/java/com/amplitude/android/internal/locators/ComposeViewTargetLocator.java

Jira ticket: https://amplitude.atlassian.net/browse/AMP-126719
With Compose update to new version it's internal implementation of testTag changed from `SemanticsModifier` to `TestTagElement`
The only common part is Inspectable Value params that we can iterate.
Tested on versions:
from 1.5.+
to 1.7.+
Supported tags:
`Modifier.testTag("some value")`
`Modifier.semantics { testTag = "some value" }`
Clickable nodes added support for clickable InspectableValue.
* Does your PR have a breaking change?:   no

fix: compose autocapture properties update

---

android/src/main/java/com/amplitude/android/storage/AndroidStorageV2.kt
android/src/main/java/com/amplitude/android/utilities/AndroidStorage.kt
android/src/test/java/com/amplitude/android/ResponseHandlerTest.kt
core/src/main/java/com/amplitude/core/Amplitude.kt
core/src/main/java/com/amplitude/core/platform/EventPipeline.kt
core/src/main/java/com/amplitude/core/utilities/EventsFileManager.kt
core/src/main/java/com/amplitude/core/utilities/FileResponseHandler.kt
core/src/main/java/com/amplitude/core/utilities/FileStorage.kt

This is a pre-requisite change prior to implementing the updated retry logic.
The goal of this PR is to revert the previous logic that doesn't align with the updated one that we want. (e.g. we're not going to modify the flushInterval on EventPipeline, and put most of the retry logic inside the Pipeline itself)

refactor: remove-previous-retry-logic

---

android/src/main/java/com/amplitude/android/storage/AndroidStorageV2.kt
android/src/main/java/com/amplitude/android/utilities/AndroidStorage.kt
android/src/test/java/com/amplitude/android/ResponseHandlerTest.kt
core/src/main/java/com/amplitude/core/Amplitude.kt
core/src/main/java/com/amplitude/core/Storage.kt
core/src/main/java/com/amplitude/core/platform/EventPipeline.kt
core/src/main/java/com/amplitude/core/utilities/EventsFileManager.kt
core/src/main/java/com/amplitude/core/utilities/ExponentialBackoffRetryHandler.kt
core/src/main/java/com/amplitude/core/utilities/FileResponseHandler.kt
core/src/main/java/com/amplitude/core/utilities/FileStorage.kt
core/src/main/java/com/amplitude/core/utilities/InMemoryResponseHandler.kt
core/src/main/java/com/amplitude/core/utilities/InMemoryStorage.kt
core/src/main/java/com/amplitude/core/utilities/http/AnalyticsResponse.kt
core/src/main/java/com/amplitude/core/utilities/http/HttpClient.kt
core/src/test/kotlin/com/amplitude/core/IdentifyInterceptTest.kt
core/src/test/kotlin/com/amplitude/core/platform/EventPipelineTest.kt
core/src/test/kotlin/com/amplitude/core/utilities/EventsFileManagerTest.kt
core/src/test/kotlin/com/amplitude/core/utilities/ExponentialBackoffRetryHandlerTest.kt
core/src/test/kotlin/com/amplitude/core/utilities/FileResponseHandlerTest.kt
core/src/test/kotlin/com/amplitude/core/utils/Mocks.kt

After removal of the old retry logic in https://github.com/amplitude/Amplitude-Kotlin/pull/258, we're now re-introducing an updated version of retrying in this PR.
We have an updated `AnalyticsResponse` with a flag to retry when upload failed. The premise is that we will retry when the event file is still present, and won't retry if it's not (e.g. bad event file).
After knowing the result of the response, we'll now **retry** within the `EventPipeline` itself through the use of `ExponentialBackoffRetryHandler`. This class contains the logic for exponential back-off delay that happens every retry attempt.
We've also updated how we're reading the event file from storage. We'll get the sorted event files again, whenever we're retrying.

fix: retry upload order

---

android/src/main/java/com/amplitude/android/utilities/DefaultEventUtils.kt

Prevent access of `DefaultEventUtils` as it's prone to misuse (e.g. Amplitude supplied `!isBuilt` yet)

fix: make DefaultEventUtils internal

---

android/src/main/java/com/amplitude/android/plugins/AndroidNetworkConnectivityCheckerPlugin.kt
android/src/main/java/com/amplitude/android/utilities/AndroidNetworkListener.kt
android/src/test/kotlin/com/amplitude/android/utilities/AndroidNetworkListenerTest.kt

When the app is backgrounded, the network actually gets blocked (`onBlockedStatusChanged(...)`). We want to set our app to offline when this happens.
As part of this PR, we've also shortened the feedback loop once the internet goes back through `onCapabilitiesChanged(...)` callback. 

fix: update network listener to cover cases where network is blocked

---

android/src/test/kotlin/com/amplitude/android/ResponseHandlerIntegrationTest.kt
core/src/main/java/com/amplitude/core/utilities/FileResponseHandler.kt
core/src/main/java/com/amplitude/core/utilities/InMemoryResponseHandler.kt
core/src/main/java/com/amplitude/core/utilities/http/AnalyticsResponse.kt
core/src/test/kotlin/com/amplitude/core/utilities/HttpClientTest.kt
core/src/test/kotlin/com/amplitude/core/utilities/http/AnalyticsResponseTest.kt
core/src/test/kotlin/com/amplitude/core/utilities/http/ResponseHandlerTest.kt

Support for common success/failure status codes in AnalyticsResponse.

fix: use range for common success/failure status codes

---

android/src/main/java/com/amplitude/android/Amplitude.kt
android/src/main/java/com/amplitude/android/Timeline.kt
android/src/main/java/com/amplitude/android/plugins/AndroidLifecyclePlugin.kt
android/src/test/kotlin/com/amplitude/android/AmplitudeRobolectricTests.kt
android/src/test/kotlin/com/amplitude/android/AmplitudeSessionTest.kt
android/src/test/kotlin/com/amplitude/android/AmplitudeTest.kt

Upon testing, this exposed function can produce these end/start session events if used incorrectly.
This PR is removing the implementation from Amplitude and moving it directly into Timeline.

fix: deprecate on enter / exit foreground

---

android/src/main/java/com/amplitude/android/Amplitude.kt
android/src/main/java/com/amplitude/android/GuardedAmplitudeFeature.kt
android/src/main/java/com/amplitude/android/InternalAmplitudeFeature.kt
android/src/main/java/com/amplitude/android/Timeline.kt
android/src/main/java/com/amplitude/android/plugins/AndroidLifecyclePlugin.kt

This pull request refactors the `Timeline` class to improve the handling of event processing and session management by introducing a `sealed class` for event messages and simplifying related logic. It also updates the `Amplitude` and `AndroidLifecyclePlugin` classes to align with these changes.
* Replaced the `EventQueueMessage` data class with a `sealed class` to better represent different types of event messages (`Event`, `EnterForeground`, and `ExitForeground`). (`[android/src/main/java/com/amplitude/android/Timeline.ktL199-R222](diffhunk://#diff-56706ffae3ed75480dd3a0d4a2ec464366e74189d50b2b3eb101904e6beeb15eL199-R222)`)
* Updated the `processEventMessage` method to handle different message types using a `when` expression, simplifying the logic for foreground and background …

fix: broken sessions forground tracking

---

android/src/main/java/com/amplitude/android/Timeline.kt
android/src/main/java/com/amplitude/android/plugins/AndroidLifecyclePlugin.kt
core/src/main/java/com/amplitude/core/events/Identify.kt
samples/kotlin-android-app/src/main/java/com/amplitude/android/sample/TroubleShootingPlugin.kt

Duplicate Sessions starts and stops
Async Foreground and background
- Moved Foreground and Background from onResume/onPause to onStart/onStop. This will prevent Foreground flag from triggering session start/stop when customer application is changing activities.
- Also we track screen viewed after the foreground is triggered to keep the event in session.
- Calling foreground/background was executed on io dispatcher. Because of this, this command was async and was in race condition with screen viewed. making foreground call not working properly.
Why removing dispatcher is safe: underlying call is just placing a new message in the Channel. Channel is thread safe by design. With this approach calling foreground and screen viewed is done from the same thread and is sync.
- Updated …

fix: async foreground and background
